---
- hosts: tomcat
  become: yes
  tasks:
    - name: Install java
      yum:
        name: java-1.8.0-openjdk
        state: present
    - name: setting default java
      alternatives:
        name: java
        path: /usr/lib/jvm/jre-1.8.0-openjdk.x86_64/bin/java
        link: /usr/bin/java
      tags: java
      