# install java 7 and 8 on centos
---
- hosts: tomcat
  become: yes
  tasks:
    - name: install java 7
      yum:
        name: java-1.7.0-openjdk
        state: present
    - name: install java 8
      yum:
        name: java-1.8.0-openjdk
        state: present