---
- hosts: tomcat
  become: yes
  vars:
    require_java: java-1.8.0-openjdk
    set_java: jre-1.8.0-openjdk
    req_tomcat_version: 9.0.68
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{req_tomcat_version.split(".")[0]}}/v{{req_tomcat_version}}/bin/apache-tomcat-{{req_tomcat_version}}.tar.gz
  tasks:
    - name: Install required java
      yum:
        name: "{{ require_java }}"
        state: present
    - name: setting default java
      ansible.builtin.alternatives:
        name: java
        path: /usr/lib/jvm/{{ set_java }}/bin/java
        link: /usr/bin/java
      tags: java
    - name: Download tomcat and unarchive tomcat
      unarchive:
        src: "{{ tomcat_url }}"
        dest: /usr/local
        remote_src: yes
    - name: Checking the tomcat path exists or not
      stat:
        path: /usr/local/apache-tomcat-{{req_tomcat_version}}
      register: tomcat_path_output
    - name: Changing the name of the tomcat
      shell:
        cmd: mv /usr/local/apache-tomcat-{{req_tomcat_version}}  /usr/local/latest
      when: tomcat_path_output.stat.exists
    - name: Start the tomcat
      shell:
        cmd: nohup /usr/local/latest/bin/startup.sh &