---
- hosts: tomcat
  become: yes
  vars:
    req_tomcat_version: 9.0.68
    tomcat_url: https://dlcdn.apache.org/tomcat/tomcat-{{req_tomcat_version.split(".")[0]}}/v{{req_tomcat_version}}/bin/apache-tomcat-{{req_tomcat_version}}.tar.gz
  tasks:
    - name: Check the tomcat version exists or not
      stat:
        path: /usr/local/apache-tomcat-{{req_tomcat_version}}
      register: tomcat_version
    - name: Rename the tomcat 
      command: mv /usr/local/apache-tomcat-{{req_tomcat_version}} /usr/local/latest
      when: tomcat_version.stat.exists